version: "3.8"
services:
  frontend:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
